package com.cooksys.flights.models;
// Generated May 14, 2016 9:10:34 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Segment generated by hbm2java
 */
@Entity
@Table(name = "segment", catalog = "flight")
public class Segment implements java.io.Serializable {

	private Integer flightId;
	private Integer flightNumber;
	private char flightStatus;
	private Date lastUpdated;
	private Set<Trip> trips = new HashSet<Trip>(0);

	public Segment() {
	}

	public Segment(Integer flightNumber, char flightStatus, Date lastUpdated) {
		this.flightNumber = flightNumber;
		this.flightStatus = flightStatus;
		this.lastUpdated = lastUpdated;
	}

	public Segment(Integer flightNumber, char flightStatus, Date lastUpdated, Set<Trip> trips) {
		this.flightNumber = flightNumber;
		this.flightStatus = flightStatus;
		this.lastUpdated = lastUpdated;
		this.trips = trips;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "flight_id", unique = true, nullable = false)
	public Integer getFlightId() {
		return this.flightId;
	}

	public void setFlightId(Integer flightId) {
		this.flightId = flightId;
	}

	@Column(name = "flight_number", nullable = false)
	public Integer getFlightNumber() {
		return this.flightNumber;
	}

	public void setFlightNumber(Integer flightNumber) {
		this.flightNumber = flightNumber;
	}

	@Column(name = "flight_status", nullable = false, length = 1)
	public char getFlightStatus() {
		return this.flightStatus;
	}

	public void setFlightStatus(char flightStatus) {
		this.flightStatus = flightStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "segments")
	public Set<Trip> getTrips() {
		return this.trips;
	}

	public void setTrips(Set<Trip> trips) {
		this.trips = trips;
	}

}
