package com.cooksys.flights.models;
// Generated May 18, 2016 8:04:28 AM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Trip generated by hbm2java
 */
@Entity
@Table(name = "trip", catalog = "flight")
public class Trip implements java.io.Serializable {

	private Integer tripId;
	private String tripName;
	private String confirmationId;
	private Date lastUpdated;
	private String orginState;
	private String orginCity;
	private String destinationState;
	private String destionationCity;
	private Integer departDay;
	private Integer arriveDay;
	private Integer numFlights;
	@JsonIgnore
	private Set<Segment> segments = new HashSet<Segment>(0);
	@JsonIgnore
	private Set<User> users = new HashSet<User>(0);

	public Trip() {
	}

	public Trip(Date lastUpdated, String orginState, String orginCity, String destinationState,
			String destionationCity, Integer departDay, Integer arriveDay, Integer numFlights) {
		this.lastUpdated = lastUpdated;
		this.orginState = orginState;
		this.orginCity = orginCity;
		this.destinationState = destinationState;
		this.destionationCity = destionationCity;
		this.departDay = departDay;
		this.arriveDay = arriveDay;
		this.numFlights = numFlights;
	}

	public Trip(String tripName, String confirmationId, Date lastUpdated, String orginState,
			String orginCity, String destinationState, String destionationCity, Integer departDay,
			Integer arriveDay, Integer numFlights, Set<Segment> segments, Set<User> users) {
		this.tripName = tripName;
		this.confirmationId = confirmationId;
		this.lastUpdated = lastUpdated;
		this.orginState = orginState;
		this.orginCity = orginCity;
		this.destinationState = destinationState;
		this.destionationCity = destionationCity;
		this.departDay = departDay;
		this.arriveDay = arriveDay;
		this.numFlights = numFlights;
		this.segments = segments;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "trip_id", unique = true, nullable = false)
	public Integer getTripId() {
		return this.tripId;
	}

	public void setTripId(Integer tripId) {
		this.tripId = tripId;
	}

	@Column(name = "trip_name", length = 45)
	public String getTripName() {
		return this.tripName;
	}

	public void setTripName(String tripName) {
		this.tripName = tripName;
	}

	@Column(name = "confirmation_id", length = 6)
	public String getConfirmationId() {
		return this.confirmationId;
	}

	public void setConfirmationId(String confirmationId) {
		this.confirmationId = confirmationId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "orgin_state", nullable = false, length = 45)
	public String getOrginState() {
		return this.orginState;
	}

	public void setOrginState(String orginState) {
		this.orginState = orginState;
	}

	@Column(name = "orgin_city", nullable = false, length = 45)
	public String getOrginCity() {
		return this.orginCity;
	}

	public void setOrginCity(String orginCity) {
		this.orginCity = orginCity;
	}

	@Column(name = "destination_state", nullable = false, length = 45)
	public String getDestinationState() {
		return this.destinationState;
	}

	public void setDestinationState(String destinationState) {
		this.destinationState = destinationState;
	}

	@Column(name = "destionation_city", nullable = false, length = 45)
	public String getDestionationCity() {
		return this.destionationCity;
	}

	public void setDestionationCity(String destionationCity) {
		this.destionationCity = destionationCity;
	}

	@Column(name = "depart_day", nullable = false)
	public Integer getDepartDay() {
		return this.departDay;
	}

	public void setDepartDay(Integer departDay) {
		this.departDay = departDay;
	}

	@Column(name = "arriveDay", nullable = false)
	public Integer getArriveDay() {
		return this.arriveDay;
	}

	public void setArriveDay(Integer arriveDay) {
		this.arriveDay = arriveDay;
	}

	@Column(name = "numFlights", nullable = false)
	public Integer getNumFlights() {
		return this.numFlights;
	}

	public void setNumFlights(Integer numFlights) {
		this.numFlights = numFlights;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "trip_segment", catalog = "flight", uniqueConstraints = {
			@UniqueConstraint(columnNames = "flight_id"),
			@UniqueConstraint(columnNames = "trip_id") }, joinColumns = {
					@JoinColumn(name = "trip_id", unique = true, nullable = false, updatable = false) }, inverseJoinColumns = {
							@JoinColumn(name = "flight_id", unique = true, nullable = false, updatable = false) })
	public Set<Segment> getSegments() {
		return this.segments;
	}

	public void setSegments(Set<Segment> segments) {
		this.segments = segments;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "trips")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
